Description: "Create CodeDeploy project"

Parameters: 
  networkStackName:
    Description: Name of the base stack with all network resources
    Type: String
    Default: nw

  permStackName:
    Description: Name of the base stack with all network resources
    Type: String
    Default: perm

  albStackName:
    Description: Name of the base stack with all network resources
    Type: String
    Default: alb

  autoscaleStackName:
    Description: Name of the base stack with all network resources
    Type: String
    Default: autoscale

  ecs1StackName:
    Description: Name of the base stack with all network resources
    Type: String
    Default: ecs-part1

  ecs2StackName:
    Description: Name of the base stack with all network resources
    Type: String
    Default: ecs-part2

  environment: 
    Type: String 
    Default: dev 
    AllowedValues: 
      - dev
      - prod 

Resources:
    
  # 
  # Create CodeDeploy application for ECS 
  # Inputs: 
  # 1) CodeDeploy Application name (from parameter store)
  # 
  codeDeployApplication: 
    Type: AWS::CodeDeploy::Application
    Properties: 
      ApplicationName: 
         !Sub '{{resolve:ssm:/${environment}/codedeploy/application_name}}'
      ComputePlatform: ECS
      Tags:
       - Key: Name
         Value: !Join [" - ", [Fn::Sub: "${AWS::StackName}", "app "] ]
       - Key: Environment
         Value: !Sub ${environment}


  # 
  # Create CodeDeploy Deployment Group using Blue Green strategy 
  # Inputs: 
  # 1) CodeDeployRole ARN for ECS access (from ECS part1 stack)
  # 2) ALB Listern ARN (from ALB stack)
  #
  # From Parameter Store:
  #  3) Target Group names (1 and 2) 
  #  4) CodeDeploy Application name 
  #  5) Deployment group name 
  #  6) ECS Cluster name 
  #  7) ECS Service name 
  # 
  codeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName:
         !Sub '{{resolve:ssm:/${environment}/codedeploy/application_name}}'
      DeploymentGroupName: !Sub '{{resolve:ssm:/${environment}/codedeploy/deploy_group_name}}'
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      AutoRollbackConfiguration:
        Enabled: true
        Events:
        - DEPLOYMENT_FAILURE
        - DEPLOYMENT_STOP_ON_REQUEST
      BlueGreenDeploymentConfiguration:
        DeploymentReadyOption:
          ActionOnTimeout: CONTINUE_DEPLOYMENT
          WaitTimeInMinutes: 0
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 60
      DeploymentStyle:
        DeploymentOption: WITH_TRAFFIC_CONTROL
        DeploymentType: BLUE_GREEN
      LoadBalancerInfo:
        TargetGroupPairInfoList:
        - ProdTrafficRoute:
           ListenerArns:
           - Fn::ImportValue: 
               Fn::Sub: "${albStackName}-LISTENER1"
        - TestTrafficRoute:
           ListenerArns:
           - Fn::ImportValue: 
               Fn::Sub: "${albStackName}-LISTENER2"
          TargetGroups:
          - Name: !Sub '{{resolve:ssm:/${environment}/alb/target_group_1}}'
          - Name: !Sub '{{resolve:ssm:/${environment}/alb/target_group_2}}'
      ServiceRoleArn: 
          Fn::ImportValue: 
             Fn::Sub: "${ecs1StackName}-CODEDEPLOY-ROLE-ARN"
      ECSServices:
      - ClusterName:
            !Sub '{{resolve:ssm:/${environment}/ecs/cluster_name}}'
        ServiceName:
            !Sub '{{resolve:ssm:/${environment}/ecs/service_name}}'
    DependsOn:
      - codeDeployApplication
    
